import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { HiArrowLeft, HiCalendar, HiClock, HiTag } from 'react-icons/hi';
import SEOHead from '../seo/SEOHead';

const BlogPost = () => {
    const { id } = useParams();
    const [post, setPost] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchPost = async () => {
            try {
                // Fetch from our local API (generated by n8n)
                const response = await fetch('/data/blogs.json');
                const blogs = await response.json();
                
                // Find the post with the matching ID (converted to string for comparison)
                const foundPost = blogs.find(b => b.id.toString() === id);
                
                if (foundPost) {
                    setPost(foundPost);
                } else {
                    setError('Post not found');
                }
            } catch (err) {
                console.error("Failed to fetch blog post:", err);
                setError('Failed to load content');
            } finally {
                setLoading(false);
            }
        };

        fetchPost();
    }, [id]);

    if (loading) return <div className="min-h-screen pt-32 text-center">Loading...</div>;
    if (error) return <div className="min-h-screen pt-32 text-center text-red-600">{error}</div>;
    if (!post) return null;

    return (
        <div className="min-h-screen bg-white pt-24 pb-16">
            <SEOHead 
                title={`${post.title} | TagSpecialist Blog`}
                description={post.excerpt || post.title}
            />
            
            <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Header */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mb-12"
                >
                    <Link to="/blogs" className="inline-flex items-center text-gray-500 hover:text-blue-600 mb-8 transition-colors">
                        <HiArrowLeft className="mr-2 w-4 h-4" />
                        Back to Blog
                    </Link>

                    <div className="flex flex-wrap gap-4 text-sm text-gray-500 mb-6">
                        <span className="flex items-center gap-1 bg-blue-50 text-blue-700 px-3 py-1 rounded-full">
                            <HiTag className="w-4 h-4" />
                            {post.category || 'Update'}
                        </span>
                        <span className="flex items-center gap-1">
                            <HiCalendar className="w-4 h-4" />
                            {new Date(post.date).toLocaleDateString()}
                        </span>
                        {post.readTime && (
                            <span className="flex items-center gap-1">
                                <HiClock className="w-4 h-4" />
                                {post.readTime}
                            </span>
                        )}
                    </div>

                    <h1 className="text-4xl md:text-5xl font-bold text-navy-900 mb-6 leading-tight">
                        {post.title}
                    </h1>
                </motion.div>

                {/* Content - Rendering simple HTML/Markdown from the API */}
                <motion.div 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.2 }}
                    className="prose prose-lg max-w-none prose-headings:text-navy-900 prose-a:text-blue-600 hover:prose-a:text-blue-700"
                >
                    {/* 
                        Security Note: For a real app, sanitize this content (e.g., DOMPurify).
                        Since this is an internal tool for a solo dev, dangerouslySetInnerHTML is acceptable for now.
                    */}
                    <div dangerouslySetInnerHTML={{ __html: post.content }} />
                </motion.div>
            </article>
        </div>
    );
};

export default BlogPost;
